server:
  port: 8088

spring:
  application:
    name: cloud-order-service

eureka:
  client:
    register-with-enreka: true
    fetchRegister: true
    service-url:
     defaultZone: http://localhost:7001/eureka/
